import {expect,it} from 'vitest';
import {newProject,replaceRange,bodyText,type FloatingObject} from '../src/core/model';
import {compose} from '../src/core/compose';
import {applyPageOperation,describePage} from '../src/core/pages';
function fixture(text:string,vertical=false){const p=replaceRange(newProject(),0,0,text);p.settings.orphanControl=false;p.settings.writingMode=vertical?'vertical':'horizontal';p.pages[0].ruling.spacingMm=10;p.pages[0].ruling.margins=vertical?{top:10,bottom:272,left:170,right:20}:{top:10,bottom:267,left:20,right:175};p.continuation=structuredClone(p.pages[0]);return p;}
const image:FloatingObject={id:'a',kind:'image',assetId:'a',anchorMode:'flow',anchorOffset:3,pageIndex:0,x:0,y:0,width:15,height:10,rotation:0,opacity:1,wrap:true,paddingMm:0,hideRuling:true,z:10};
for(const vertical of [false,true])it(`duplicates a naturally full page ending in newline without blank pages (${vertical})`,()=>{const p=fixture('AAA\nBBB\nCCC',vertical),layout=compose(p,()=>5);expect(layout.pages).toHaveLength(2);const n=applyPageOperation(p,layout,{type:'duplicate',index:0},()=>5);expect(bodyText(n)).toBe('AAA\nBBB\n\fAAA\nBBB\n\fCCC');expect(compose(n,()=>5).pages).toHaveLength(3);});
it('deletes the images actually displayed on the selected page',()=>{const p=fixture('ABCDEFGHI');p.objects=[image];const layout=compose(p,()=>5);expect(layout.objects[0].actualPage).toBe(0);expect(describePage(p,layout,0).objects).toHaveLength(1);expect(applyPageOperation(p,layout,{type:'delete',index:0},()=>5).objects).toHaveLength(0);expect(applyPageOperation(p,layout,{type:'delete',index:1},()=>5).objects).toHaveLength(1);});
it('later anchors follow preceding wrapping images without self-chasing',()=>{const p=fixture('ABCDEFGHI');p.objects=[{...image,anchorOffset:0},{...image,id:'b',anchorOffset:3,wrap:false}];const l=compose(p,()=>5);expect(l.objects.map(o=>o.actualPage)).toEqual([0,1]);expect(l.pages.length).toBeLessThan(5);const reordered=compose({...p,objects:p.objects.map(o=>({...o,z:-o.z}))},()=>5);expect(reordered.objects.map(o=>[o.actualX,o.actualY,o.actualPage])).toEqual(l.objects.map(o=>[o.actualX,o.actualY,o.actualPage]));});
it('page duplication retains displayed image position and flow mode',()=>{const p=fixture('ABCDEFGHI');p.objects=[image];const original=compose(p,()=>5);const n=applyPageOperation(p,original,{type:'duplicate',index:0},()=>5),l=compose(n,()=>5);expect(l.objects).toHaveLength(2);expect(l.objects.map(o=>[o.actualPage,o.actualX,o.actualY,o.anchorMode])).toEqual([[0,20,20,'flow'],[1,20,20,'flow']]);expect(l.pages).toHaveLength(original.pages.length+1);});
