import {useState} from 'react';
import type {Project} from '../core/model';
import type {Layout} from '../core/compose';
import {applyBodyFormat} from '../core/text-format';
import {Modal} from './Modal';
import {FontSelect} from './FontSelect';
export function BodyFormatDialog({project,layout,index,fonts,recent,onClose,onApply}:{project:Project;layout:Layout;index:number;fonts:string[];recent:string[];onClose:()=>void;onApply:(p:Project)=>boolean}){
 const [scope,setScope]=useState<'page'|'all'>('page'),[size,setSize]=useState(project.baseStyle.sizePt),[family,setFamily]=useState(project.baseStyle.fontFamily),[useSize,setUseSize]=useState(true),[useFont,setUseFont]=useState(false),[boxes,setBoxes]=useState(false),[error,setError]=useState('');
 return <Modal title="本文の書式を一括変更" onClose={onClose}><label className="field">変更する範囲<select aria-label="変更する範囲" value={scope} onChange={e=>setScope(e.target.value as 'page'|'all')}><option value="page">このページの本文</option><option value="all">すべての本文</option></select></label><label className="check-label"><input type="checkbox" checked={useSize} onChange={e=>setUseSize(e.target.checked)}/>文字サイズを揃える</label><label className="field">文字サイズ（pt）<input type="number" min={6} max={72} disabled={!useSize} value={size} onChange={e=>setSize(Number(e.target.value))}/></label><label className="check-label"><input type="checkbox" checked={useFont} onChange={e=>setUseFont(e.target.checked)}/>フォントを揃える</label><div className="field"><label htmlFor="bulk-font">一括変更するフォント</label><FontSelect id="bulk-font" value={family} onChange={setFamily} fonts={fonts} recent={recent}/></div><label className="check-label"><input type="checkbox" checked={boxes} onChange={e=>setBoxes(e.target.checked)}/>対象範囲の文字箱も変更する</label><p className="help-text">色・太字・斜体・下線は維持します。変更後の文字サイズに合わせて、本文の折り返しと自動罫線を計算し直します。</p>{error&&<p role="alert">{error}</p>}<div className="dialog-actions"><button onClick={onClose}>キャンセル</button><button className="primary" disabled={!useSize&&!useFont} onClick={()=>{try{const next=applyBodyFormat(project,{...(useSize?{sizePt:size}:{}),...(useFont?{fontFamily:family}:{})},{scope,pageIndex:index,layout,includeTextBoxes:boxes});if(onApply(next))onClose();}catch(e){setError(String(e));}}}>一括変更する</button></div></Modal>;
}
