import {useEffect,useState,type ReactNode} from 'react';
import type {Project,TextStyle} from '../core/model';
import {FontSelect} from './FontSelect';
import {ColorPalette} from './ColorPalette';
import {SaveIcon} from './SaveIcon';
type Tab='file'|'home'|'insert'|'layout'|'view'|'help'|'object';
interface Props {
 project:Project;style:TextStyle;mixedSize?:boolean;mixedSpacing?:boolean;fonts:string[];recent:string[];status:string;canUndo:boolean;canRedo:boolean;hasSelection:boolean;context:string|null;zoom:number;thumbnails:boolean;
 onFormat:(style:Partial<TextStyle>)=>void;onSettings:(patch:Partial<Project['settings']>)=>void;onStandardFont:(font:string)=>void;onStandardSize:(size:number)=>void;
 onZoom:(value:number)=>void;onThumbnails:(value:boolean)=>void;onUndo:(redo?:boolean)=>void;onClipboard:(action:'cut'|'copy'|'paste')=>void;
 onAction:(action:'save'|'saveAs'|'open'|'recent'|'files'|'new'|'stationery'|'image'|'text'|'break'|'page'|'visual'|'bulk'|'history'|'output'|'preferences')=>void;
}
export function RibbonGroup({label,children}:{label:string;children:ReactNode}){return <section className="ribbon-group"><div className="ribbon-group-controls">{children}</div><div className="ribbon-group-label">{label}</div></section>;}
export function EditorRibbon(p:Props){
 const [tab,setTab]=useState<Tab>('home');
 const [sizeDraft,setSizeDraft]=useState<string|null>(null);
 const [spacingDraft,setSpacingDraft]=useState<string|null>(null),[baseSizeDraft,setBaseSizeDraft]=useState<string|null>(null);
 useEffect(()=>setSpacingDraft(null),[p.style.letterSpacingPt,p.mixedSpacing]);
 useEffect(()=>setBaseSizeDraft(null),[p.project.baseStyle.sizePt]);
 useEffect(()=>setSizeDraft(null),[p.style.sizePt,p.mixedSize]);
 useEffect(()=>{if(p.context)setTab('object');else setTab(t=>t==='object'?'home':t);},[p.context]);
 const tabs:[Tab,string][]=[['file','ファイル'],['home','ホーム'],['insert','挿入'],['layout','レイアウト'],['view','表示'],['help','ヘルプ'],...(p.context?[['object',p.context] as [Tab,string]]:[])];
 const action=(key:Parameters<Props['onAction']>[0],label:string,icon?:ReactNode)=><button className={icon?'ribbon-large':''} onMouseDown={e=>e.preventDefault()} onClick={()=>p.onAction(key)}>{icon&&<span className="ribbon-icon" aria-hidden="true">{icon}</span>}{label}</button>;
 return <div className="editor-ribbon">
  <header className="ribbon-titlebar"><div className="brand"><img className="brand-logo-image" src="/brand/letterier-header-logo.png" alt=""/><strong>レタリエ</strong></div><div className="quick-actions"><button aria-label="保存" title="保存（Ctrl+S）" onClick={()=>p.onAction('save')}><SaveIcon/> 保存</button><button disabled={!p.canUndo} aria-label="元に戻す" title="元に戻す（Ctrl+Z）" onMouseDown={e=>e.preventDefault()} onClick={()=>p.onUndo()}>↶</button><button disabled={!p.canRedo} aria-label="やり直す" title="やり直す（Ctrl+Y）" onMouseDown={e=>e.preventDefault()} onClick={()=>p.onUndo(true)}>↷</button></div><button className="document-title" onClick={()=>p.onAction('files')}>{p.project.title}</button><span className="save-status" role="status" title={p.status}>{p.status}</span>{action('output','PDF・印刷')}</header>
  <div className="ribbon-tabs" role="tablist" aria-label="編集リボン">{tabs.map(([id,label])=><button key={id} id={'tab-'+id} role="tab" aria-selected={tab===id} aria-controls="ribbon-panel" tabIndex={tab===id?0:-1} onClick={()=>setTab(id)} onKeyDown={e=>{if(['ArrowLeft','ArrowRight','Home','End'].includes(e.key)){e.preventDefault();const i=tabs.findIndex(t=>t[0]===id),n=e.key==='Home'?0:e.key==='End'?tabs.length-1:(i+(e.key==='ArrowRight'?1:-1)+tabs.length)%tabs.length;setTab(tabs[n][0]);document.getElementById('tab-'+tabs[n][0])?.focus();}}}>{label}</button>)}</div>
  <div id="ribbon-panel" className="ribbon-panel" role="tabpanel" aria-labelledby={'tab-'+tab}>
   {tab==='file'&&<><RibbonGroup label="手紙">{action('new','新規作成','✉')}{action('open','ファイルを開く…','▱')}{action('recent','最近使った手紙')}</RibbonGroup><RibbonGroup label="ファイル保存">{action('save','保存',<SaveIcon/>)}{action('saveAs','名前を付けて保存…')}{action('history','保存履歴')}</RibbonGroup><RibbonGroup label="出力">{action('output','PDF・印刷','▤')}</RibbonGroup></>}
   {tab==='home'&&<><RibbonGroup label="クリップボード"><button className="ribbon-large" onMouseDown={e=>e.preventDefault()} onClick={()=>p.onClipboard('paste')}><span className="ribbon-icon" aria-hidden="true">▤</span>貼り付け</button><div className="ribbon-stack"><button disabled={!p.hasSelection} onMouseDown={e=>e.preventDefault()} onClick={()=>p.onClipboard('cut')}>✂ 切り取り</button><button disabled={!p.hasSelection} onMouseDown={e=>e.preventDefault()} onClick={()=>p.onClipboard('copy')}>▱ コピー</button></div></RibbonGroup>
    <RibbonGroup label="フォント"><div className="ribbon-font"><div className="ribbon-row"><label className="sr-only" htmlFor="font">選択部分のフォント</label><FontSelect id="font" value={p.style.fontFamily} onChange={fontFamily=>p.onFormat({fontFamily})} fonts={p.fonts} recent={p.recent}/><input aria-label="文字サイズ（pt）" type="number" min={6} max={72} value={sizeDraft??(p.mixedSize?'':p.style.sizePt)} onBlur={()=>setSizeDraft(null)} onChange={e=>{setSizeDraft(e.target.value);const sizePt=Number(e.target.value);if(sizePt>=6&&sizePt<=72)p.onFormat({sizePt});}}/></div><div className="ribbon-row format-buttons">{(['bold','italic','underline'] as const).map((key,i)=><button key={key} aria-label={['太字','斜体','下線'][i]} aria-pressed={p.style[key]} onMouseDown={e=>e.preventDefault()} onClick={()=>p.onFormat({[key]:!p.style[key]})}>{['B','I','U'][i]}</button>)}<ColorPalette label="文字の色" value={p.style.color} onChange={color=>p.onFormat({color})}/></div></div></RibbonGroup>
    <RibbonGroup label="本文の書式"><div className="ribbon-stack"><label>文字間隔（pt）<input aria-label="文字間隔（pt）" type="number" min={0} max={12} step={.5} value={spacingDraft??(p.mixedSpacing?'':p.style.letterSpacingPt??0)} onBlur={()=>setSpacingDraft(null)} onChange={e=>{setSpacingDraft(e.target.value);const letterSpacingPt=Number(e.target.value);if(e.target.value!==''&&Number.isFinite(letterSpacingPt)&&letterSpacingPt>=0&&letterSpacingPt<=12)p.onFormat({letterSpacingPt});}}/></label><span>選択した文字／次に入力する文字</span>{action('bulk','本文の書式を一括変更…')}</div></RibbonGroup><RibbonGroup label="便箋">{action('new','新規作成','✉')}{action('stationery','便箋変更','❀')}</RibbonGroup></>}
   {tab==='insert'&&<><RibbonGroup label="配置する要素">{action('image','写真・画像','▧')}{action('text','文字箱','T')}</RibbonGroup><RibbonGroup label="ページ">{action('break','ここから次のページ','▱')}{action('page','複製・移動・削除…')}</RibbonGroup></>}
   {tab==='layout'&&<><RibbonGroup label="用紙"><div className="ribbon-stack"><label>用紙<select aria-label="用紙" value={p.project.settings.paper} onChange={e=>p.onSettings({paper:e.target.value as Project['settings']['paper']})}><option value="A4">A4</option><option value="B5">B5</option><option value="POSTCARD">はがき</option></select></label><label>用紙の向き<select aria-label="用紙の向き" value={p.project.settings.orientation} onChange={e=>p.onSettings({orientation:e.target.value as 'portrait'|'landscape'})}><option value="portrait">縦向き</option><option value="landscape">横向き</option></select></label></div></RibbonGroup><RibbonGroup label="文字の流れ"><div className="ribbon-stack"><label>書字方向<select aria-label="書字方向" value={p.project.settings.writingMode} onChange={e=>p.onSettings({writingMode:e.target.value as 'horizontal'|'vertical'})}><option value="horizontal">横書き</option><option value="vertical">縦書き</option></select></label><label>縦中横<select aria-label="縦中横" value={p.style.verticalInlineMode} onChange={e=>p.onFormat({verticalInlineMode:e.target.value as TextStyle['verticalInlineMode']})}><option value="auto">2桁数字を自動で横並び</option><option value="tate-chu-yoko">選んだ文字を横並びに</option><option value="normal">通常の縦配置</option></select></label></div></RibbonGroup><RibbonGroup label="便箋・罫線">{action('visual','背景・罫線・余白…','☷')}{action('stationery','便箋変更','❀')}</RibbonGroup><RibbonGroup label="標準フォント"><div className="ribbon-stack ribbon-default-style"><label htmlFor="base-font">本文の標準フォント</label><FontSelect id="base-font" value={p.project.baseStyle.fontFamily} onChange={p.onStandardFont} fonts={p.fonts} recent={p.recent}/><label>本文の標準サイズ（pt）<input aria-label="本文の標準サイズ（pt）" type="number" min={6} max={72} value={baseSizeDraft??p.project.baseStyle.sizePt} onBlur={()=>setBaseSizeDraft(null)} onChange={e=>{setBaseSizeDraft(e.target.value);const size=Number(e.target.value);if(Number.isFinite(size)&&size>=6&&size<=72)p.onStandardSize(size);}}/></label><label title="段落がページをまたぐとき、最初や最後の1行が単独になるのをできるだけ防ぎます。"><input type="checkbox" checked={p.project.settings.orphanControl} onChange={e=>p.onSettings({orphanControl:e.target.checked})}/>段落の最初・最後の1行を別ページに分けない</label></div></RibbonGroup></>}
   {tab==='view'&&<><RibbonGroup label="表示倍率"><label>表示<select aria-label="表示倍率" value={p.zoom} onChange={e=>p.onZoom(Number(e.target.value))}>{Array.from({length:16},(_,i)=>(50+i*5)/100).map(v=><option key={v} value={v}>{Math.round(v*100)}%</option>)}</select></label></RibbonGroup><RibbonGroup label="ページ一覧"><label><input type="checkbox" checked={p.thumbnails} onChange={e=>p.onThumbnails(e.target.checked)}/>ページ一覧を表示</label></RibbonGroup><RibbonGroup label="操作画面">{action('preferences','設定・使い方')}</RibbonGroup></>}
   {tab==='help'&&<><RibbonGroup label="設定・使い方">{action('preferences','設定・使い方','?')}</RibbonGroup><RibbonGroup label="保存と出力">{action('history','保存履歴')}{action('output','PDF・印刷')}</RibbonGroup></>}
   {tab==='object'&&<><RibbonGroup label={p.context??'配置した要素'}><span>移動・拡縮は用紙上で、細かな設定は右側で調整できます。</span></RibbonGroup><RibbonGroup label="挿入">{action('image','写真・画像')}{action('text','文字箱')}</RibbonGroup></>}
  </div>
 </div>;
}
