import {useEffect,useRef,useState} from 'react';
import {Modal} from './Modal';
export interface FrameSource {name:string;count:number;unit?:string;thumbnail:(index:number)=>Promise<string>}
export function FrameDialog({source,onChoose}:{source:FrameSource;onChoose:(index:number|null)=>void}){
 const unit=source.unit??'コマ';
 const [selected,setSelected]=useState(0),[thumbnails,setThumbnails]=useState<{index:number;data:string}[]>([]),[preview,setPreview]=useState(''),[error,setError]=useState('');
 useEffect(()=>{let alive=true;void(async()=>{const indexes=Array.from({length:Math.min(20,source.count)},(_,i)=>Math.round(i*(source.count-1)/Math.max(1,Math.min(20,source.count)-1)));for(const index of indexes){if(!alive)return;try{const data=await source.thumbnail(index);if(alive)setThumbnails(old=>[...old,{index,data}]);}catch{if(alive)setError('コマの表示に失敗しました。この素材が壊れていないか確認してください。');return;}}})();return()=>{alive=false;};},[source]);
 useEffect(()=>{let alive=true;setPreview('');void source.thumbnail(selected).then(data=>{if(alive)setPreview(data);}).catch(()=>{if(alive)setError('このコマを読み取れません。別のコマを選んでください。');});return()=>{alive=false;};},[selected,source]);
 return <Modal title={`使用する${unit}を選択`} wide onClose={()=>onChoose(null)}><p>{source.name} ／ {source.count}{unit}。一覧から選ぶか、番号を指定できます。</p><div className="frame-layout"><div className="frame-thumbnails">{thumbnails.map(t=><button key={t.index} aria-pressed={selected===t.index} onClick={()=>setSelected(t.index)}><img src={t.data} alt=""/><span>{t.index+1}{unit}目</span></button>)}</div><div className="frame-detail">{preview&&<img className="frame-preview" src={preview} alt={`${selected+1}${unit}目のプレビュー`}/>}<label className="field">{unit}番号<input type="number" min={1} max={source.count} value={selected+1} onChange={e=>{const n=Number(e.target.value);if(Number.isInteger(n)&&n>=1&&n<=source.count){setSelected(n-1);setError('');}}}/></label></div></div>{error&&<p role="alert">{error}</p>}<div className="dialog-actions"><button onClick={()=>onChoose(null)}>キャンセル</button><button className="primary" disabled={!preview||!!error} onClick={()=>onChoose(selected)}>この{unit}を使う</button></div><p className="help-text">選んだ{unit}を静止画像として置きます。元の素材も手紙ファイルに保存します。</p></Modal>;
}
export function useFramePicker(){const [source,setSource]=useState<FrameSource|null>(null),resolve=useRef<((index:number|null)=>void)|null>(null);useEffect(()=>()=>{resolve.current?.(null);},[]);return {choose:(value:FrameSource)=>new Promise<number|null>(done=>{resolve.current=done;setSource(value);}),dialog:source?<FrameDialog source={source} onChoose={index=>{setSource(null);resolve.current?.(index);resolve.current=null;}}/>:null};}
