import { useState } from 'react';
import {FontSelect} from './FontSelect';
import type { FloatingObject,Project } from '../core/model';
import type { PlacedObject } from '../core/compose';
export function ObjectProperties({object,project,pageCount,fonts,recentFonts,onChange,onDelete,onDuplicate,onMode,onClose}:{object:PlacedObject;project:Project;pageCount:number;fonts:string[];recentFonts:string[];onChange:(patch:Partial<FloatingObject>)=>void;onDelete:()=>void;onDuplicate:()=>void;onMode:(mode:FloatingObject['anchorMode'])=>void;onClose:()=>void}){
  const [ratio,setRatio]=useState(true);
  const number=(label:string,key:'x'|'y'|'width'|'height'|'rotation'|'paddingMm',min:number,max:number)=><div className="field"><label>{label}<input aria-label={label} type="number" min={min} max={max} step={key==='rotation'?1:.5} value={Math.round(object[key]*10)/10} onChange={e=>{const n=Number(e.target.value);if(n<min||n>max)return;const patch:Partial<FloatingObject>={[key]:n};if(ratio&&object.kind==='image'){if(key==='width')patch.height=Math.min(500,Math.max(1,n*object.height/object.width));if(key==='height')patch.width=Math.min(500,Math.max(1,n*object.width/object.height));}onChange(patch);}}/></label></div>;
  return <><div className="panel-title">{object.kind==='image'?'画像':'自由配置の文字箱'}<button className="small-button" onClick={onClose}>本文へ</button></div>{object.kind==='image'?<p className="help-text">{project.assets[object.assetId!]?.name}</p>:<><label className="field">文字箱の本文<textarea aria-label="文字箱の本文" rows={5} maxLength={10000} value={object.text??''} onChange={e=>onChange({text:e.target.value})}/></label><div className="field"><label htmlFor="object-font">文字箱のフォント</label><FontSelect id="object-font" value={object.style?.fontFamily??project.baseStyle.fontFamily} fonts={fonts} recent={recentFonts} onChange={fontFamily=>onChange({style:{...project.baseStyle,...object.style,fontFamily}})}/></div><div className="format-buttons">{([ ['bold','太字'],['italic','斜体'],['underline','下線'] ] as const).map(([key,label])=><button key={key} aria-pressed={object.style?.[key]??project.baseStyle[key]} onClick={()=>onChange({style:{...project.baseStyle,...object.style,[key]:!(object.style?.[key]??project.baseStyle[key])}})}>{label}</button>)}</div><div className="field"><label>文字箱のサイズ（pt）<input aria-label="文字箱のサイズ（pt）" type="number" min={6} max={72} value={object.style?.sizePt??14} onChange={e=>{const sizePt=Number(e.target.value);if(sizePt>=6&&sizePt<=72)onChange({style:{...project.baseStyle,...object.style,sizePt}});}}/></label></div><label className="field">文字箱の色<input type="color" value={object.style?.color??project.baseStyle.color} onChange={e=>onChange({style:{...project.baseStyle,...object.style,color:e.target.value}})}/></label></>}
    <div className="field"><label>配置方法<select aria-label="配置方法" value={object.anchorMode} onChange={e=>onMode(e.target.value as FloatingObject['anchorMode'])}><option value="flow">本文へ追従</option><option value="page">ページの位置へ固定</option></select></label></div>{object.anchorMode==='page'&&<div className="field"><label>配置ページ<select aria-label="配置ページ" value={object.pageIndex} onChange={e=>onChange({pageIndex:Number(e.target.value)})}>{Array.from({length:pageCount},(_,index)=><option key={index} value={index}>{index+1}ページ</option>)}</select></label></div>}<p className="help-text">{object.anchorMode==='flow'?'位置は関連する本文からの距離です。':'位置は用紙の左上からの距離です。配置ページを選ぶと、画像・写真を別のページへ移動できます。'} 画面上ではドラッグ、選択後は矢印キーでも移動できます。</p>
    <div className="field-pair">{number('横位置（mm）','x',-1000,1000)}{number('縦位置（mm）','y',-1000,1000)}{number('幅（mm）','width',1,500)}{number('高さ（mm）','height',1,500)}</div>{object.kind==='image'&&<label className="check-label"><input type="checkbox" checked={ratio} onChange={e=>setRatio(e.target.checked)}/>縦横比を保つ</label>}{number('回転（度）','rotation',-360,360)}
    <label className="field">不透明度 {Math.round(object.opacity*100)}%<input aria-label="要素の不透明度" type="range" min={0} max={100} value={Math.round(object.opacity*100)} onChange={e=>onChange({opacity:Number(e.target.value)/100})}/></label>
    <label className="check-label"><input type="checkbox" checked={object.wrap} onChange={e=>onChange({wrap:e.target.checked})}/>本文を周囲へ回り込ませる</label>{number('周囲の余白（mm）','paddingMm',0,50)}<label className="check-label"><input type="checkbox" checked={object.hideRuling} onChange={e=>onChange({hideRuling:e.target.checked})}/>周囲の罫線を隠す</label>
    <div className="object-order"><button onClick={()=>onChange({z:Math.min(80,Math.max(...project.objects.map(o=>o.z))+1)})}>最前面</button><button onClick={()=>onChange({z:Math.max(1,Math.min(...project.objects.map(o=>o.z))-1)})}>最背面</button><button onClick={()=>onChange({z:Math.min(80,object.z+1)})}>前面へ</button><button onClick={()=>onChange({z:Math.max(1,object.z-1)})}>背面へ</button><button onClick={onDuplicate}>複製</button><button className="danger" onClick={onDelete}>削除</button></div>
  </>;
}
