import { useState } from 'react';
import { describePage,type PageOperation } from '../core/pages';
import type { Project } from '../core/model';
import type { Layout } from '../core/compose';
import { Modal } from './Modal';
export function PageOperationDialog({project,layout,index,onClose,onApply}:{project:Project;layout:Layout;index:number;onClose:()=>void;onApply:(op:PageOperation)=>void}){
  const info=describePage(project,layout,index),[operation,setOperation]=useState<'duplicate'|'move'|'delete'>('duplicate'),[target,setTarget]=useState(index);
  return <Modal title={`${index+1}ページの操作`} onClose={onClose}><p>このページにある次の内容を、まとめて操作します。あとから「元に戻す」で操作全体を戻せます。</p><div className="page-summary"><strong>本文 {info.text.length}文字</strong><small>本文の位置 {info.start+1}〜{Math.max(info.start+1,info.end)}{info.partialParagraph?'（段落の途中を含みます）':''}</small><pre>{info.text||'本文はありません。'}</pre><strong>一緒に操作する要素 {info.objects.length}個</strong><ul>{info.objects.map(o=><li key={o.id}>{o.kind==='image'?project.assets[o.assetId!]?.name??'画像':`文字箱「${o.text?.slice(0,35)}」`} ／ {o.anchorMode==='flow'?'本文に追従':'ページ固定'}</li>)}</ul></div><div className="field"><label htmlFor="page-operation">操作</label><select id="page-operation" value={operation} onChange={e=>setOperation(e.target.value as typeof operation)}><option value="duplicate">このページの次に複製</option><option value="move">別の位置へ移動</option><option value="delete">このページを削除</option></select></div>{operation==='move'&&<div className="field"><label htmlFor="page-target">移動後のページ位置</label><select id="page-target" value={target} onChange={e=>setTarget(Number(e.target.value))}>{layout.pages.map((_,i)=><option key={i} value={i}>{i+1}ページ目</option>)}</select></div>}<p className="help-text">操作時点の各ページの区切りを手動改ページとして残します。本文は引き続き編集でき、追記すると次のページへ広がります。</p><div className="dialog-actions"><button onClick={onClose}>キャンセル</button><button className={operation==='delete'?'danger':'primary'} disabled={operation==='move'&&target===index} onClick={()=>onApply(operation==='move'?{type:'move',index,target}:{type:operation,index})}>{operation==='duplicate'?'複製する':operation==='move'?'移動する':'内容を確認して削除する'}</button></div></Modal>;
}
