import {useEffect,useMemo,useState} from 'react';
import {templates,createFromTemplate,applyBuiltinTemplateDesign,applyUserTemplateDesign} from '../core/templates';
import {designsFor} from '../core/stationery-designs';
import {resolveStationeryArtwork} from '../core/stationery-artwork';
import {replaceRange,type Project} from '../core/model';
import {TemplateRepository,type UserTemplate} from '../persistence/templates';
import {PlatformStorage} from '../persistence/platform';
import {ReadonlyPages} from './ReadonlyPages';
import {PaperDecoration} from './PaperDecoration';
import {measureText} from './typography';
import {Modal} from './Modal';
import type {UiLanguage} from '../i18n';
export function TemplateDialog({project,language,onClose,onNew,onApply,purpose='new',index=0,pageCount=1,onOpen,onRecent,onRecover}:{project:Project;language:UiLanguage;onClose:()=>void;onNew:(p:Project)=>Promise<boolean>;onApply:(p:Project)=>boolean;purpose?:'new'|'change';index?:number;pageCount?:number;onOpen?:()=>void;onRecent?:()=>void;onRecover?:()=>void}){
 const repository=useMemo(()=>new TemplateRepository(new PlatformStorage()),[]);
 const [family,setFamily]=useState('すべて'),[season,setSeason]=useState('すべて'),[chosen,setChosen]=useState('washi'),[mode,setMode]=useState(project.settings.writingMode);
 const [user,setUser]=useState<UserTemplate[]>([]),[custom,setCustom]=useState<Project|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 const [register,setRegister]=useState(false),[name,setName]=useState(''),[withText,setWithText]=useState(false),[remove,setRemove]=useState(false);
 const [updateId,setUpdateId]=useState<string|null>(null);
 const [design,setDesign]=useState(1),[cycle,setCycle]=useState(false);
 const [scope,setScope]=useState<'all'|'page'|'range'>('all'),[first,setFirst]=useState(index+1),[last,setLast]=useState(index+1);
 const run=async(f:()=>Promise<void>)=>{setBusy(true);setError('');try{await f();}catch(e){setError(e instanceof Error?e.message:String(e));}finally{setBusy(false);}};
 useEffect(()=>{void run(async()=>setUser(await repository.list()));},[repository]);
 const builtin=templates.find(t=>t.id===chosen),saved=user.find(t=>t.id===chosen);
 const available=designsFor(builtin?.id??'').filter(entry=>resolveStationeryArtwork(entry.id));
 const choice=builtin&&available.length>1?{design,cycle:cycle&&available.length===5}:undefined;
 const sample=language==='ja'?'季節の移ろいを感じる頃となりました。\nいかがお過ごしでしょうか。\n\n心を込めて、お便りいたします。\f続きのページは、控えめな飾りで。\n言葉をゆっくり綴る余白を大切に。':'I hope this letter finds you well.\nThe changing season brought you to mind.\n\nWith warmest wishes, I wanted to write.\fThe second page keeps the decoration quiet,\nleaving generous space for your words.';
 const preview=useMemo(()=>custom??replaceRange(createFromTemplate(builtin?.id??'washi',mode,choice),0,0,sample),[custom,builtin,mode,sample,design,cycle]);
 return <Modal title={purpose==='new'?'新規作成':'便箋変更'} wide onClose={onClose}>
 {purpose==='new'&&<div className="template-start-actions">{onOpen&&<button onClick={onOpen}>ファイルを開く…</button>}{onRecent&&<button onClick={onRecent}>最近使った手紙</button>}{onRecover&&<button onClick={onRecover}>前回の回復用データを開く</button>}</div>}
 <div className="template-filters"><label>種類 <select aria-label="種類" value={family} onChange={e=>setFamily(e.target.value)}>{['すべて','和風','洋風','自分のテンプレート'].map(s=><option key={s} value={s}>{s}</option>)}</select></label>{family!=='自分のテンプレート'&&<label>季節 <select aria-label="季節" value={season} onChange={e=>setSeason(e.target.value)}>{['すべて','通年','春','夏','秋','冬'].map(s=><option key={s} value={s}>{s}</option>)}</select></label>}<button disabled={busy} onClick={()=>{setRegister(!register);setUpdateId(null);setRemove(false);}}>今の便箋を登録…</button></div>
 {saved&&!register&&<button disabled={busy} onClick={()=>{setUpdateId(saved.id);setName(saved.name);setWithText(saved.withText);setRegister(true);}}>今の便箋で登録を更新…</button>}
 {register&&<form className="template-register" onSubmit={e=>{e.preventDefault();void run(async()=>{const entry=updateId?await repository.update(updateId,name,project,withText,measureText):await repository.add(name,project,withText,measureText);setUser(await repository.list());setCustom(await repository.open(entry.id));setChosen(entry.id);setRegister(false);setUpdateId(null);setFamily('自分のテンプレート');setName('');});}}><label>名前 <input value={name} onChange={e=>setName(e.target.value)} maxLength={80} required/></label><label className="check-label"><input type="checkbox" checked={withText} onChange={e=>setWithText(e.target.checked)}/>本文・文字箱も含めて登録</label><small>チェックしない場合、本文と文字箱を除き、画像・背景・罫線を登録します。</small>{updateId&&<p>選択した登録を現在の手紙のデザインで更新します。作成済みの手紙は変更しません。</p>}<button disabled={busy}>{updateId?'更新する':'登録する'}</button><button type="button" disabled={busy} onClick={()=>{setRegister(false);setUpdateId(null);}}>キャンセル</button></form>}
 <div className="template-layout"><div className="template-grid">{family==='自分のテンプレート'?<>{!user.length&&<p>まだ登録されていません。</p>}{user.map(t=><button key={t.id} aria-pressed={chosen===t.id} disabled={busy} onClick={()=>void run(async()=>{setCustom(await repository.open(t.id));setChosen(t.id);setRemove(false);})}><span className="template-user-icon">✉</span><strong translate="no">{t.name}</strong><small>{t.withText?'本文を含む':'デザインのみ'}</small></button>)}</>:templates.filter(t=>(family==='すべて'||t.family===family)&&(season==='すべて'||t.season===season)).map(t=>{
   return <button key={t.id} aria-pressed={chosen===t.id} onClick={()=>{setChosen(t.id);setDesign(1);setCustom(null);setRemove(false);}}><div className="template-thumbnail" style={{background:t.paper}}><PaperDecoration design={`${t.id}-first`} width={210} height={297} writingMode={mode}/><svg width="100%" height="100%" viewBox="0 0 210 297"><g stroke={t.color} strokeWidth=".35">{Array.from({length:12},(_,i)=><path key={i} d={mode==='horizontal'?`M20 ${36+i*16}H190`:`M${180-i*13} 20V277`}/>)}</g></svg></div><strong>{t.name}</strong><small>{t.family} · {t.season}</small></button>;
 })}</div><div className="template-detail"><strong translate={builtin?undefined:"no"}>{builtin?.name??saved?.name}</strong><p>{builtin?.description??'登録した便箋から、新しい手紙を作れます。'}</p>{builtin&&<><label className="preview-zoom">プレビューの書字方向 <select value={mode} onChange={e=>setMode(e.target.value as typeof mode)}><option value="horizontal">横書き</option><option value="vertical">縦書き</option></select></label><label>図案<select aria-label="図案" value={design} onChange={e=>setDesign(Number(e.target.value))}>{available.map(entry=><option key={entry.id} value={entry.number}>{entry.number} — {language==='ja'?entry.nameJa:entry.nameEn}</option>)}</select></label><label className="check-label"><input type="checkbox" checked={cycle&&available.length===5} disabled={available.length!==5} onChange={e=>setCycle(e.target.checked)}/>続きのページで5図案を順番に使う</label></>}<div className="template-preview"><ReadonlyPages project={preview} zoom={.32}/></div><small>最初のページと、続きのページ</small></div></div>
 {error&&<p role="alert" className="warning">{error}</p>}
 {remove&&saved&&<p className="warning">{`「${saved.name}」の登録を削除します。`}<button disabled={busy} onClick={()=>void run(async()=>{await repository.remove(saved.id);setUser(await repository.list());setChosen('washi');setCustom(null);setRemove(false);})}>登録を削除する</button><button onClick={()=>setRemove(false)}>戻る</button></p>}
 {purpose==='change'&&<div className="template-apply-scope"><label>適用する範囲<select aria-label="適用する範囲" value={scope} onChange={e=>setScope(e.target.value as typeof scope)}><option value="all">すべてのページ</option><option value="page">このページ</option><option value="range">指定したページ範囲</option></select></label>{scope==='range'&&<><label>開始ページ<input aria-label="開始ページ" type="number" min={1} max={pageCount} value={first} onChange={e=>setFirst(Number(e.target.value))}/></label><label>終了ページ<input aria-label="終了ページ" type="number" min={first} max={pageCount} value={last} onChange={e=>setLast(Number(e.target.value))}/></label></>}</div>}
 <div className="dialog-actions">{saved&&<button className="danger" disabled={busy} onClick={()=>setRemove(true)}>登録を削除…</button>}{purpose==='change'&&(builtin||custom)&&<button className="primary" disabled={busy} onClick={()=>{try{const target=scope==='all'?'all':scope==='page'?{start:index,end:index}:{start:first-1,end:last-1};const next=custom?applyUserTemplateDesign(project,custom,measureText,target):applyBuiltinTemplateDesign(project,builtin!.id,measureText,target,choice);if(onApply(next))onClose();}catch(e){setError(e instanceof Error?e.message:String(e));}}}>今の手紙にデザインを適用</button>}{purpose==='new'&&<button className="primary" disabled={busy||(!builtin&&!custom)} onClick={()=>void run(async()=>{const p=builtin?createFromTemplate(builtin.id,mode,choice):await repository.open(chosen);if(await onNew(p))onClose();})}>この便箋で新しい手紙</button>}</div><p className="help-text">便箋変更では、本文・書式・自分で追加した写真を保持し、選択した範囲の背景・罫線・余白と便箋の飾りを変更します。「元に戻す」で戻せます。新規作成の前には、未保存の変更を保存するか確認します。</p>
 </Modal>;
}
