// Resolve only artwork that actually exists. Brief catalog membership does not
// imply that an illustration has been made or reviewed.
const series=new Set(['blank','washi','ichimatsu','sakura','nanohana','asagao','goldfish','momiji','moon','snow-garden','camellia','classic','dots','mimosa','tulip','seaside','lemon','autumn-leaf','woodland','snowflake','christmas']);
const illustratedVariants:Record<string,{primary:string;companion:string}>={
 'dots-v2':{primary:'dots-v2',companion:'dots-v2-companion'},
 'dots-v3':{primary:'dots-v3',companion:'dots-v3-companion'},
 'dots-v4':{primary:'dots-v4',companion:'dots-v4-companion'},
 'dots-v5':{primary:'dots-v5',companion:'dots-v5-companion'},
 'classic-v2':{primary:'classic-v2',companion:'classic-v2-companion'},
 'classic-v3':{primary:'classic-v3',companion:'classic-v3-companion'},
 'classic-v4':{primary:'classic-v4',companion:'classic-v4-companion'},
 'classic-v5':{primary:'classic-v5',companion:'classic-v5-companion'},
 'washi-v2':{primary:'washi-v2',companion:'washi-v2-companion'},
 'washi-v3':{primary:'washi-v3',companion:'washi-v3-companion'},
 'washi-v4':{primary:'washi-v4',companion:'washi-v4-companion'},
 'washi-v5':{primary:'washi-v5',companion:'washi-v5-companion'},
 'ichimatsu-v2':{primary:'ichimatsu-v2',companion:'ichimatsu-v2-companion'},
 'ichimatsu-v3':{primary:'ichimatsu-v3',companion:'ichimatsu-v3-companion'},
 'ichimatsu-v4':{primary:'ichimatsu-v4',companion:'ichimatsu-v4-companion'},
 'ichimatsu-v5':{primary:'ichimatsu-v5',companion:'ichimatsu-v5-companion'},
 'snowflake-v2':{primary:'snowflake-v2',companion:'snowflake-v2-companion'},
 'snowflake-v3':{primary:'snowflake-v3',companion:'snowflake-v3-companion'},
 'snowflake-v4':{primary:'snowflake-v4',companion:'snowflake-v4-companion'},
 'snowflake-v5':{primary:'snowflake-v5',companion:'snowflake-v5-companion'},
 'christmas-v2':{primary:'christmas-v2',companion:'christmas-v2-companion'},
 'christmas-v3':{primary:'christmas-v3',companion:'christmas-v3-companion'},
 'christmas-v4':{primary:'christmas-v4',companion:'christmas-v4-companion'},
 'christmas-v5':{primary:'christmas-v5',companion:'christmas-v5-companion'},
 'autumn-leaf-v2':{primary:'autumn-leaf-v2',companion:'autumn-leaf-v2-companion'},
 'autumn-leaf-v3':{primary:'autumn-leaf-v3',companion:'autumn-leaf-v3-companion'},
 'autumn-leaf-v4':{primary:'autumn-leaf-v4',companion:'autumn-leaf-v4-companion'},
 'autumn-leaf-v5':{primary:'autumn-leaf-v5',companion:'autumn-leaf-v5-companion'},
 'woodland-v2':{primary:'woodland-v2',companion:'woodland-v2-companion'},
 'woodland-v3':{primary:'woodland-v3',companion:'woodland-v3-companion'},
 'woodland-v4':{primary:'woodland-v4',companion:'woodland-v4-companion'},
 'woodland-v5':{primary:'woodland-v5',companion:'woodland-v5-companion'},
 'seaside-v2':{primary:'seaside-v2',companion:'seaside-v2-companion'},
 'seaside-v3':{primary:'seaside-v3',companion:'seaside-v3-companion'},
 'seaside-v4':{primary:'seaside-v4',companion:'seaside-v4-companion'},
 'seaside-v5':{primary:'seaside-v5',companion:'seaside-v5-companion'},
 'lemon-v2':{primary:'lemon-v2',companion:'lemon-v2-companion'},
 'lemon-v3':{primary:'lemon-v3',companion:'lemon-v3-companion'},
 'lemon-v4':{primary:'lemon-v4',companion:'lemon-v4-companion'},
 'lemon-v5':{primary:'lemon-v5',companion:'lemon-v5-companion'},
 'mimosa-v2':{primary:'mimosa-v2',companion:'mimosa-v2-companion'},
 'mimosa-v3':{primary:'mimosa-v3',companion:'mimosa-v3-companion'},
 'mimosa-v4':{primary:'mimosa-v4',companion:'mimosa-v4-companion'},
 'mimosa-v5':{primary:'mimosa-v5',companion:'mimosa-v5-companion'},
 'tulip-v2':{primary:'tulip-v2',companion:'tulip-v2-companion'},
 'tulip-v3':{primary:'tulip-v3',companion:'tulip-v3-companion'},
 'tulip-v4':{primary:'tulip-v4',companion:'tulip-v4-companion'},
 'tulip-v5':{primary:'tulip-v5',companion:'tulip-v5-companion'},
 'snow-garden-v2':{primary:'snow-garden-v2',companion:'snow-garden-v2-companion'},
 'snow-garden-v3':{primary:'snow-garden-v3',companion:'snow-garden-v3-companion'},
 'snow-garden-v4':{primary:'snow-garden-v4',companion:'snow-garden-v4-companion'},
 'snow-garden-v5':{primary:'snow-garden-v5',companion:'snow-garden-v5-companion'},
 'camellia-v2':{primary:'camellia-v2',companion:'camellia-v2-companion'},
 'camellia-v3':{primary:'camellia-v3',companion:'camellia-v3-companion'},
 'camellia-v4':{primary:'camellia-v4',companion:'camellia-v4-companion'},
 'camellia-v5':{primary:'camellia-v5',companion:'camellia-v5-companion'},
 'moon-v2':{primary:'moon-v2',companion:'moon-v2-companion'},
 'moon-v3':{primary:'moon-v3',companion:'moon-v3-companion'},
 'moon-v4':{primary:'moon-v4',companion:'moon-v4-companion'},
 'moon-v5':{primary:'moon-v5',companion:'moon-v5-companion'},
 'momiji-v2':{primary:'momiji-v2',companion:'momiji-v2-companion'},
 'momiji-v3':{primary:'momiji-v3',companion:'momiji-v3-companion'},
 'momiji-v4':{primary:'momiji-v4',companion:'momiji-v4-companion'},
 'momiji-v5':{primary:'momiji-v5',companion:'momiji-v5-companion'},
 'goldfish-v2':{primary:'goldfish-v2',companion:'goldfish-v2-companion'},
 'goldfish-v3':{primary:'goldfish-v3',companion:'goldfish-v3-companion'},
 'goldfish-v4':{primary:'goldfish-v4',companion:'goldfish-v4-companion'},
 'goldfish-v5':{primary:'goldfish-v5',companion:'goldfish-v5-companion'},
 'sakura-v2':{primary:'sakura-v2',companion:'sakura-v2-companion'},
 'sakura-v3':{primary:'sakura-v3',companion:'sakura-v3-companion'},
 'sakura-v4':{primary:'sakura-v4',companion:'sakura-v4-companion'},
 'sakura-v5':{primary:'sakura-v5',companion:'sakura-v5-companion'},
 'nanohana-v2':{primary:'nanohana-v2',companion:'nanohana-v2-companion'},
 'nanohana-v3':{primary:'nanohana-v3',companion:'nanohana-v3-companion'},
 'nanohana-v4':{primary:'nanohana-v4',companion:'nanohana-v4-companion'},
 'nanohana-v5':{primary:'nanohana-v5',companion:'nanohana-v5-companion'},
 'asagao-v2':{primary:'asagao-v2',companion:'asagao-v2-companion'},
 'asagao-v3':{primary:'asagao-v3',companion:'asagao-v3-companion'},
 'asagao-v4':{primary:'asagao-v4',companion:'asagao-v4-companion'},
 'asagao-v5':{primary:'asagao-v5',companion:'asagao-v5-companion'},
};
export interface StationeryArtwork {id:string;continuation:boolean;variant?:number;primary?:string;companion?:string}
export function resolveStationeryArtwork(design:string):StationeryArtwork|null {
 const numbered=/^(.+)-v([1-5])$/.exec(design);
 if(numbered){
  if(!series.has(numbered[1]))return null;
  if(numbered[2]==='1')return {id:numbered[1],continuation:false,variant:1};
  const art=illustratedVariants[design];
  return art?{id:numbered[1],continuation:false,variant:Number(numbered[2]),...art}:null;
 }
 const id=design.replace(/-(first|continuation)$/,'');
 return series.has(id)?{id,continuation:design.endsWith('-continuation')}:null;
}
